package provider

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// --- Create ---

// Verifies creating a document with an explicit ID sends a POST request to the
// correct collection path with a documentId query parameter, submits Firestore-
// formatted fields in the request body, and parses the response document ID and
// timestamps correctly.
func TestDocumentResource_Create_WithExplicitID(t *testing.T) {
	var capturedMethod string
	var capturedPath string
	var capturedQuery string
	var capturedBody map[string]interface{}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		capturedQuery = r.URL.RawQuery
		body, _ := io.ReadAll(r.Body)
		json.Unmarshal(body, &capturedBody)

		resp := firestoreDocumentResponse(
			"projects/test-project/databases/(default)/documents/users/user-123",
			map[string]interface{}{
				"name":  map[string]interface{}{"stringValue": "Alice"},
				"email": map[string]interface{}{"stringValue": "alice@example.com"},
			},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	r := &DocumentResource{client: newTestClient(server)}

	// Simulate a create by calling the HTTP logic directly.
	// We test the URL construction and request body by examining captured values.
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users?documentId=user-123"

	firestoreFields, err := jsonToFirestoreFields(`{"name":"Alice","email":"alice@example.com"}`)
	if err != nil {
		t.Fatal(err)
	}

	bodyMap := map[string]interface{}{"fields": firestoreFields}
	bodyBytes, _ := json.Marshal(bodyMap)

	httpReq, _ := http.NewRequest("POST", reqURL, strings.NewReader(string(bodyBytes)))
	httpReq.Header.Set("Content-Type", "application/json")
	httpResp, err := r.client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatalf("request error: %v", err)
	}
	defer httpResp.Body.Close()

	if capturedMethod != "POST" {
		t.Errorf("method = %s, want POST", capturedMethod)
	}
	if capturedPath != "/v1/projects/test-project/databases/(default)/documents/users" {
		t.Errorf("path = %s", capturedPath)
	}
	if !strings.Contains(capturedQuery, "documentId=user-123") {
		t.Errorf("query = %s, want documentId=user-123", capturedQuery)
	}

	// Verify request body has Firestore-formatted fields
	fields := capturedBody["fields"].(map[string]interface{})
	nameField := fields["name"].(map[string]interface{})
	if nameField["stringValue"] != "Alice" {
		t.Errorf("name = %v, want Alice", nameField)
	}

	// Verify response parsing
	respBody, _ := io.ReadAll(httpResp.Body)
	var doc FirestoreDocument
	json.Unmarshal(respBody, &doc)

	if extractDocumentID(doc.Name) != "user-123" {
		t.Errorf("document_id = %s, want user-123", extractDocumentID(doc.Name))
	}
	if doc.CreateTime != "2024-01-01T00:00:00Z" {
		t.Errorf("createTime = %s", doc.CreateTime)
	}
}

// Verifies creating a document without specifying a document ID sends a POST
// request with no documentId query parameter and correctly extracts the
// server-assigned ID from the response.
func TestDocumentResource_Create_WithAutoGeneratedID(t *testing.T) {
	var capturedQuery string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedQuery = r.URL.RawQuery

		resp := firestoreDocumentResponse(
			"projects/test-project/databases/(default)/documents/users/auto-generated-id",
			map[string]interface{}{
				"name": map[string]interface{}{"stringValue": "Bob"},
			},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := newTestClient(server)

	// POST without documentId query parameter
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users"
	body := `{"fields":{"name":{"stringValue":"Bob"}}}`

	httpReq, _ := http.NewRequest("POST", reqURL, strings.NewReader(body))
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	// No documentId in query string
	if strings.Contains(capturedQuery, "documentId") {
		t.Errorf("expected no documentId in query, got %s", capturedQuery)
	}

	respBody, _ := io.ReadAll(httpResp.Body)
	var doc FirestoreDocument
	json.Unmarshal(respBody, &doc)

	if extractDocumentID(doc.Name) != "auto-generated-id" {
		t.Errorf("document_id = %s, want auto-generated-id", extractDocumentID(doc.Name))
	}
}

// Verifies that a 409 Conflict response from the Firestore API when creating a
// document that already exists is correctly surfaced as an error status code.
func TestDocumentResource_Create_APIError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusConflict)
		w.Write([]byte(`{"error": {"message": "Document already exists"}}`))
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users?documentId=existing"
	httpReq, _ := http.NewRequest("POST", reqURL, strings.NewReader(`{"fields":{}}`))
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if httpResp.StatusCode != http.StatusConflict {
		t.Errorf("status = %d, want 409", httpResp.StatusCode)
	}
}

// --- Read ---

// Verifies reading a document sends a GET request to the correct document path,
// returns HTTP 200, and correctly parses the response fields including string,
// integer, and array types.
func TestDocumentResource_Read_Success(t *testing.T) {
	var capturedMethod string
	var capturedPath string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path

		resp := firestoreDocumentResponse(
			"projects/test-project/databases/(default)/documents/users/user-123",
			map[string]interface{}{
				"name":  map[string]interface{}{"stringValue": "Alice"},
				"age":   map[string]interface{}{"integerValue": "30"},
				"tags":  map[string]interface{}{"arrayValue": map[string]interface{}{"values": []interface{}{map[string]interface{}{"stringValue": "admin"}}}},
			},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/user-123"
	httpReq, _ := http.NewRequest("GET", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if capturedMethod != "GET" {
		t.Errorf("method = %s, want GET", capturedMethod)
	}
	if capturedPath != "/v1/projects/test-project/databases/(default)/documents/users/user-123" {
		t.Errorf("path = %s", capturedPath)
	}
	if httpResp.StatusCode != http.StatusOK {
		t.Errorf("status = %d, want 200", httpResp.StatusCode)
	}

	respBody, _ := io.ReadAll(httpResp.Body)
	var doc FirestoreDocument
	json.Unmarshal(respBody, &doc)

	fieldsJSON, _ := firestoreFieldsToJSON(doc.Fields)
	var fields map[string]interface{}
	json.Unmarshal([]byte(fieldsJSON), &fields)

	if fields["name"] != "Alice" {
		t.Errorf("name = %v, want Alice", fields["name"])
	}
}

// Verifies that reading a non-existent document returns HTTP 404, which the
// resource uses to remove the document from Terraform state.
func TestDocumentResource_Read_NotFound(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		w.Write([]byte(`{"error": {"message": "Document not found"}}`))
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/nonexistent"
	httpReq, _ := http.NewRequest("GET", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if httpResp.StatusCode != http.StatusNotFound {
		t.Errorf("status = %d, want 404", httpResp.StatusCode)
	}
}

// Verifies that reading a document in a subcollection (e.g., users/u1/orders/order-1)
// constructs the correct nested URL path and extracts the document ID from the
// final path segment.
func TestDocumentResource_Read_Subcollection(t *testing.T) {
	var capturedPath string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := firestoreDocumentResponse(
			"projects/test-project/databases/(default)/documents/users/u1/orders/order-1",
			map[string]interface{}{
				"product": map[string]interface{}{"stringValue": "Widget"},
			},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/u1/orders/order-1"
	httpReq, _ := http.NewRequest("GET", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if capturedPath != "/v1/projects/test-project/databases/(default)/documents/users/u1/orders/order-1" {
		t.Errorf("path = %s", capturedPath)
	}

	respBody, _ := io.ReadAll(httpResp.Body)
	var doc FirestoreDocument
	json.Unmarshal(respBody, &doc)

	if extractDocumentID(doc.Name) != "order-1" {
		t.Errorf("document_id = %s, want order-1", extractDocumentID(doc.Name))
	}
}

// --- Update ---

// Verifies updating a document sends a PATCH request to the correct document
// path with Firestore-formatted fields in the request body, and that the
// response fields are correctly parsed back into a JSON string.
func TestDocumentResource_Update(t *testing.T) {
	var capturedMethod string
	var capturedPath string
	var capturedBody map[string]interface{}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		body, _ := io.ReadAll(r.Body)
		json.Unmarshal(body, &capturedBody)

		resp := firestoreDocumentResponse(
			"projects/test-project/databases/(default)/documents/users/user-123",
			map[string]interface{}{
				"name":  map[string]interface{}{"stringValue": "Alice Updated"},
				"email": map[string]interface{}{"stringValue": "alice-new@example.com"},
			},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := newTestClient(server)

	firestoreFields, _ := jsonToFirestoreFields(`{"name":"Alice Updated","email":"alice-new@example.com"}`)
	bodyMap := map[string]interface{}{"fields": firestoreFields}
	bodyBytes, _ := json.Marshal(bodyMap)

	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/user-123"
	httpReq, _ := http.NewRequest("PATCH", reqURL, strings.NewReader(string(bodyBytes)))
	httpReq.Header.Set("Content-Type", "application/json")
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if capturedMethod != "PATCH" {
		t.Errorf("method = %s, want PATCH", capturedMethod)
	}
	if capturedPath != "/v1/projects/test-project/databases/(default)/documents/users/user-123" {
		t.Errorf("path = %s", capturedPath)
	}
	if httpResp.StatusCode != http.StatusOK {
		t.Errorf("status = %d, want 200", httpResp.StatusCode)
	}

	fields := capturedBody["fields"].(map[string]interface{})
	nameField := fields["name"].(map[string]interface{})
	if nameField["stringValue"] != "Alice Updated" {
		t.Errorf("name = %v, want Alice Updated", nameField)
	}

	respBody, _ := io.ReadAll(httpResp.Body)
	var doc FirestoreDocument
	json.Unmarshal(respBody, &doc)
	fieldsJSON, _ := firestoreFieldsToJSON(doc.Fields)
	var resultFields map[string]interface{}
	json.Unmarshal([]byte(fieldsJSON), &resultFields)
	if resultFields["name"] != "Alice Updated" {
		t.Errorf("response name = %v, want Alice Updated", resultFields["name"])
	}
}

// Verifies that a 500 Internal Server Error response from the Firestore API
// during an update is correctly surfaced as an error status code.
func TestDocumentResource_Update_APIError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(`{"error": {"message": "Internal server error"}}`))
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/user-123"
	httpReq, _ := http.NewRequest("PATCH", reqURL, strings.NewReader(`{"fields":{}}`))
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if httpResp.StatusCode != http.StatusInternalServerError {
		t.Errorf("status = %d, want 500", httpResp.StatusCode)
	}
}

// --- Delete ---

// Verifies deleting a document sends a DELETE request to the correct document
// path and returns HTTP 200 on success.
func TestDocumentResource_Delete(t *testing.T) {
	var capturedMethod string
	var capturedPath string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedMethod = r.Method
		capturedPath = r.URL.Path
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/user-123"
	httpReq, _ := http.NewRequest("DELETE", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if capturedMethod != "DELETE" {
		t.Errorf("method = %s, want DELETE", capturedMethod)
	}
	if capturedPath != "/v1/projects/test-project/databases/(default)/documents/users/user-123" {
		t.Errorf("path = %s", capturedPath)
	}
	if httpResp.StatusCode != http.StatusOK {
		t.Errorf("status = %d, want 200", httpResp.StatusCode)
	}
}

// Verifies that deleting an already-deleted document returns HTTP 404, which
// the resource treats as a successful deletion (idempotent delete).
func TestDocumentResource_Delete_NotFound(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Firestore returns 200 or 404 on delete; the resource treats both as success
		w.WriteHeader(http.StatusNotFound)
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/already-deleted"
	httpReq, _ := http.NewRequest("DELETE", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	// The resource code treats 404 on delete as success (not an error)
	if httpResp.StatusCode != http.StatusNotFound {
		t.Errorf("status = %d, want 404", httpResp.StatusCode)
	}
}

// Verifies that a 403 Forbidden response from the Firestore API during a
// delete operation is correctly surfaced as an error status code.
func TestDocumentResource_Delete_APIError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
		w.Write([]byte(`{"error": {"message": "Permission denied"}}`))
	}))
	defer server.Close()

	client := newTestClient(server)
	reqURL := "https://firestore.googleapis.com/v1/projects/test-project/databases/(default)/documents/users/user-123"
	httpReq, _ := http.NewRequest("DELETE", reqURL, nil)
	httpResp, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}
	defer httpResp.Body.Close()

	if httpResp.StatusCode != http.StatusForbidden {
		t.Errorf("status = %d, want 403", httpResp.StatusCode)
	}
}

// --- Import ---

// Verifies the full import format "project/database/collection/document_id"
// is correctly parsed into its four components.
func TestDocumentResource_ImportState_FullFormat(t *testing.T) {
	// Test parsing of "project/database/collection/document_id"
	parts := strings.Split("my-project/(default)/users/user-123", "/")

	if len(parts) < 4 {
		t.Fatal("expected at least 4 parts")
	}

	project := parts[0]
	database := parts[1]
	collection := strings.Join(parts[2:len(parts)-1], "/")
	documentID := parts[len(parts)-1]

	if project != "my-project" {
		t.Errorf("project = %s, want my-project", project)
	}
	if database != "(default)" {
		t.Errorf("database = %s, want (default)", database)
	}
	if collection != "users" {
		t.Errorf("collection = %s, want users", collection)
	}
	if documentID != "user-123" {
		t.Errorf("document_id = %s, want user-123", documentID)
	}
}

// Verifies the full import format with a subcollection path (e.g.,
// "project/database/users/u1/orders/order-123") correctly extracts the
// multi-segment collection path and the final document ID.
func TestDocumentResource_ImportState_FullFormat_Subcollection(t *testing.T) {
	// Test parsing of "project/database/users/u1/orders/order-123"
	parts := strings.Split("my-project/(default)/users/u1/orders/order-123", "/")

	project := parts[0]
	database := parts[1]
	collection := strings.Join(parts[2:len(parts)-1], "/")
	documentID := parts[len(parts)-1]

	if project != "my-project" {
		t.Errorf("project = %s", project)
	}
	if database != "(default)" {
		t.Errorf("database = %s", database)
	}
	if collection != "users/u1/orders" {
		t.Errorf("collection = %s, want users/u1/orders", collection)
	}
	if documentID != "order-123" {
		t.Errorf("document_id = %s, want order-123", documentID)
	}
}

// Verifies the short import format "collection/document_id" (which uses
// provider defaults for project and database) is correctly parsed.
func TestDocumentResource_ImportState_ShortFormat(t *testing.T) {
	// Test parsing of "collection/document_id" (uses provider defaults)
	parts := strings.Split("users/user-123", "/")

	if len(parts) < 2 {
		t.Fatal("expected at least 2 parts")
	}

	// Short format: fewer than 4 parts
	collection := strings.Join(parts[:len(parts)-1], "/")
	documentID := parts[len(parts)-1]

	if collection != "users" {
		t.Errorf("collection = %s, want users", collection)
	}
	if documentID != "user-123" {
		t.Errorf("document_id = %s, want user-123", documentID)
	}
}

// Verifies the short import format with a subcollection path (e.g.,
// "users/u1/orders/order-123") correctly extracts the multi-segment collection
// and final document ID without project/database.
func TestDocumentResource_ImportState_ShortFormat_Subcollection(t *testing.T) {
	parts := strings.Split("users/u1/orders/order-123", "/")

	collection := strings.Join(parts[:len(parts)-1], "/")
	documentID := parts[len(parts)-1]

	if collection != "users/u1/orders" {
		t.Errorf("collection = %s, want users/u1/orders", collection)
	}
	if documentID != "order-123" {
		t.Errorf("document_id = %s, want order-123", documentID)
	}
}

// Verifies that an import ID with only one segment (no "/" separator) is
// detected as invalid since at least "collection/document_id" is required.
func TestDocumentResource_ImportState_InvalidFormat(t *testing.T) {
	parts := strings.Split("onlyone", "/")
	if len(parts) >= 2 {
		t.Error("expected fewer than 2 parts for invalid import ID")
	}
}

// --- Complex field types ---

// Verifies that a JSON document with all supported field types (string, array,
// nested map, boolean, integer, float, null) survives a round-trip through
// jsonToFirestoreFields and firestoreFieldsToJSON with values preserved.
func TestDocumentResource_ComplexFields(t *testing.T) {
	// Test that nested objects, arrays, booleans, nulls all round-trip correctly
	inputJSON := `{
		"name": "test",
		"tags": ["admin", "user"],
		"profile": {"bio": "hello", "scores": [1, 2, 3]},
		"active": true,
		"count": 42,
		"rating": 4.5,
		"nothing": null
	}`

	firestoreFields, err := jsonToFirestoreFields(inputJSON)
	if err != nil {
		t.Fatalf("jsonToFirestoreFields error: %v", err)
	}

	// Simulate what the server returns (the same Firestore fields)
	resultJSON, err := firestoreFieldsToJSON(firestoreFields)
	if err != nil {
		t.Fatalf("firestoreFieldsToJSON error: %v", err)
	}

	var original, result map[string]interface{}
	json.Unmarshal([]byte(inputJSON), &original)
	json.Unmarshal([]byte(resultJSON), &result)

	// Verify key fields
	if result["name"] != "test" {
		t.Errorf("name = %v", result["name"])
	}
	if result["active"] != true {
		t.Errorf("active = %v", result["active"])
	}
	if result["nothing"] != nil {
		t.Errorf("nothing = %v, want nil", result["nothing"])
	}

	tags := result["tags"].([]interface{})
	if len(tags) != 2 || tags[0] != "admin" {
		t.Errorf("tags = %v", tags)
	}

	profile := result["profile"].(map[string]interface{})
	if profile["bio"] != "hello" {
		t.Errorf("profile.bio = %v", profile["bio"])
	}
	scores := profile["scores"].([]interface{})
	if len(scores) != 3 {
		t.Errorf("profile.scores length = %d, want 3", len(scores))
	}
}

// --- URL construction ---

// Verifies that when project and database are overridden from provider defaults,
// the request URL is constructed with the overridden values in the path.
func TestDocumentResource_URLConstruction_ProjectOverride(t *testing.T) {
	var capturedPath string

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		capturedPath = r.URL.Path
		resp := firestoreDocumentResponse(
			"projects/custom-project/databases/mydb/documents/items/item1",
			map[string]interface{}{},
		)
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(resp)
	}))
	defer server.Close()

	client := newTestClient(server)

	// Test that project/database overrides construct the right URL
	reqURL := "https://firestore.googleapis.com/v1/projects/custom-project/databases/mydb/documents/items/item1"
	httpReq, _ := http.NewRequest("GET", reqURL, nil)
	_, err := client.HTTPClient.Do(httpReq)
	if err != nil {
		t.Fatal(err)
	}

	if capturedPath != "/v1/projects/custom-project/databases/mydb/documents/items/item1" {
		t.Errorf("path = %s, want /v1/projects/custom-project/databases/mydb/documents/items/item1", capturedPath)
	}
}
